# Publish the NuGet package to GitHub Packages.
# Workflow runs when a version tag is pushed.

name: Publish NuGet Package

on:
  push:
    tags: [v*]
  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build and pack
        run: dotnet build --configuration Release

      - name: NuGet Push
        run: dotnet nuget push src/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
