# Workflow to register a new application version with GitHub Releases.

name: Release Tracking

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: github_release
        uses: docker://ghcr.io/anton-yurchenko/git-release:v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX_REGEX: "prod\/"

      - name: Show GitHub response
        run: echo ${{ steps.github_release.outputs.response }}
